# S-AI-BER Project Configuration

# LLM stuff yaaayyy
llm:
  provider: "" # or "google", "anthropic", whatever
  model_name: ""
  api_key: "" # Use env var here for sure
  temperature: 0.2

# DB paths: logging, session data, agent registry, and reports
database:
  agent_registry_path: "./database/agent_registry.json"
  logs_dir: "./database/logs/"
  sessions_dir: "./database/sessions/"
  reports_dir: "./database/reports/"

# Security, i.e. allowed target scopes. Empty list means no restrictions (Dont do)
security:
  allowed_target_scopes:
    - "192.168.1.0/24"
    - "10.0.0.0/8"